---
title: "R Notebook"
output: html_notebook
---

```{r}
#clear enviro, run libraries
rm(list = ls())
library(tidyverse)
library(here)
library(ggplot2)
```


```{r}
#pull in data
DF <- read.csv(here("Data", "Kip Practice Trees.csv"))
```


1. Pivot the dataframe
```{r}
Kip_dens <- DF %>% pivot_longer(cols = c('Densiometer', 'CanopyApp'), names_to = "Method")
```



2. Build a box plot

```{r}
ggplot(Kip_dens, aes(Method, value)) +
  geom_boxplot() +
  geom_point(aes(color = "grey")) +
  xlab("Method") +
  ylab("Value") +
  theme_bw()
```


3. Build a bar graph
```{r}
#make a dataframe
Dense <- Kip_dens %>% group_by(Method) %>%
  summarize(mean_dens = mean(value, na.rm = T),
            sd_dens = sd(value, na.rm = T))
```

```{r}
#plot the dataframe
ggplot(Dense, aes(Method, mean_dens)) +
  geom_col() +
  geom_errorbar(aes
    (ymin = mean_dens - sd_dens, ymax = mean_dens + sd_dens)
  ) +
  xlab("Method") +
  ylab("Value") +
  theme_bw()
```

4. Calculate confidence intervals

```{r}
#CI for densiometer method

sample <- DF %>% group_by(PointNumber) %>%
  summarize(Total = length(unique(PointNumber))) #can see that there are 9 points, so that means the sample size is 9

#sample size n = 9 
#sample mean x = 91.10222
#sample sd s = 5.800843 
#found mean and sd values from looking at Dense dataframe 


n <- 9
xbar <- 91.10222
s <- 5.800843

margin <- qt(0.975,df=n-1)*s/sqrt(n)

lowerinterval <- xbar - margin
lowerinterval 

#the lower interval is 86.643

upperinterval <- xbar + margin
upperinterval 

#the upper interval is 95.56114

#The confidence interval of 95% for the densiometer method is [86.643, 95.56114]
```


```{r}
#CI for CanopyApp method

sample <- DF %>% group_by(PointNumber) %>%
  summarize(Total = length(unique(PointNumber))) #can see that there are 9 points, so that means the sample size is 9

#sample size n = 9 
#sample mean x = 87.59344
#sample sd s = 6.366887
#found mean and sd values from looking at Dense dataframe 


t <- 9
ybar <- 87.59344
e <- 6.366887

marginal <- qt(0.975,df=t-1)*e/sqrt(t)

lowinterval <- ybar - marginal
lowinterval 

#the lower interval is 82.69942

upinterval <- ybar + marginal
upinterval 

#the upper interval is 92.48746

#The confidence interval of 95% for the densiometer method is [82.69942, 92.48746]
```

5. Plot the confidence intervals

First, add the CI values to the Dense dataframe
```{r}
CImin <- c(82.69942, 86.6433)
new_dense <- cbind(Dense, CImin)

CImax <- c(92.48746, 95.56114)
new_dense <- cbind(new_dense, CImax)
```


Now plot the CI values 
```{r}
ggplot(new_dense, aes(Method, mean_dens)) +
  geom_col() +
  geom_errorbar(aes
    (ymin = CImin, ymax = CImax), 
    width = 0.2,
    size = 0.5,
    color = "blue", 
  ) +
  xlab("Method") +
  ylab("Value") +
  theme_bw()
```




Some previous attempts
```{r}
#make a dataframe with point number, densiometer, and canopyapp
forplotting <- DF %>% group_by(PointNumber, Densiometer, CanopyApp) %>%
  summarize(Point = length(unique(PointNumber)))
```



```{r}
ggplot(forplotting, aes(Densiometer, CanopyApp)) +
  geom_point() +
  geom_smooth(method = lm, level = 0.95) +
  xlab("Densiometer") +
  ylab("CanopyApp") +
  theme_bw()
```

```{r}
#now I'm going to try to make a bar chart version plotting the CI for densiometer
ggplot(Dense, aes(Method, mean_dens)) +
  geom_col() +
  geom_errorbar(aes
    (ymin = lowerinterval, ymax = upperinterval)) +
  xlab("Method") +
  ylab("Value") +
  theme_bw()
```

```{r}
#and now plotting the CI for canopyapp
ggplot(Dense, aes(Method, mean_dens)) +
  geom_col() +
  geom_errorbar(aes
    (ymin = lowinterval, ymax = upinterval)) +
  xlab("Method") +
  ylab("Value") +
  theme_bw()
```


6. Now lets use stats to compare the methods 

First I'll run an ANOVA
```{r}
myanova <- aov(value ~ Method, data = Kip_dens)
summary(myanova)
anova(myanova)
```


Now let's run a linear regression (anova)
```{r}
mylm <- lm(value ~ Method, Kip_dens)
summary(mylm)
anova(mylm)
```

Now a general linear model (anova)
```{r}
myglm <- glm(value ~ Method, family = gaussian, data = Kip_dens)
summary(myglm)
anova(myglm)
```




